name: my_education
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: ^2.24.2
  google_sign_in: 6.2.1
  firebase_auth: 4.16.0
  cloud_firestore: 4.14.0
  flutter: 
    sdk: flutter
  get_cli: ^1.8.1

dev_dependencies: 
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

