name: my_education
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: ^2.24.2
  google_sign_in: 6.2.1
  firebase_auth: 4.16.0
  cloud_firestore: 4.14.0
  firebase_storage: 11.6.0
  get_cli: ^1.8.1
  textfield_datepicker: 0.2.0
  intl: 0.18.0
  google_nav_bar: 5.0.6
  image_picker: 1.0.7
  platform_file: 0.0.1
  file_picker: 6.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

