// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsRozQljhoiSzjEvRx7Ib3ltkjUhtM6aw',
    appId: '1:879348636134:web:8b4e8279ff1bc9b90ade27',
    messagingSenderId: '879348636134',
    projectId: 'myeducation-9c9a9',
    authDomain: 'myeducation-9c9a9.firebaseapp.com',
    storageBucket: 'myeducation-9c9a9.appspot.com',
    measurementId: 'G-W7GNNEHGGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApJns55VL7QBbJ-9NRFlh-NJ_-z-IOSFQ',
    appId: '1:879348636134:android:17c7108d88bd87b10ade27',
    messagingSenderId: '879348636134',
    projectId: 'myeducation-9c9a9',
    storageBucket: 'myeducation-9c9a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMaFwLjtOsPrKFS7eZW9H2Hl9vbvMExfw',
    appId: '1:879348636134:ios:b04668f96e5dd33a0ade27',
    messagingSenderId: '879348636134',
    projectId: 'myeducation-9c9a9',
    storageBucket: 'myeducation-9c9a9.appspot.com',
    androidClientId: '879348636134-ajq7vttbhqiiuffio4rjun5l5rs4i4dr.apps.googleusercontent.com',
    iosClientId: '879348636134-b2f5l9n7mistfhqkmjtlb2hla53te52q.apps.googleusercontent.com',
    iosBundleId: 'com.example.myEducation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMaFwLjtOsPrKFS7eZW9H2Hl9vbvMExfw',
    appId: '1:879348636134:ios:92c83e7fdd29d1f50ade27',
    messagingSenderId: '879348636134',
    projectId: 'myeducation-9c9a9',
    storageBucket: 'myeducation-9c9a9.appspot.com',
    androidClientId: '879348636134-ajq7vttbhqiiuffio4rjun5l5rs4i4dr.apps.googleusercontent.com',
    iosClientId: '879348636134-k6b4kpm8frecc4am4ihm47813k453dnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myEducation.RunnerTests',
  );
}
